#services:
#  vtools:
#    image: vtools
#    build:
#      context: .
#      dockerfile: VTools/Dockerfile

version: "3.8"
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user-vTools-dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vTools
    ports:
      - 5432:5432
  dbmigration:
    image: dbmigration
    build:
      context: .
      dockerfile: DbMigration/Dockerfile
