
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user-vTools-dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vTools
    ports:
      - 5432:5432
  dbmigration:
    image: dbmigration:latest
    build:
      context: .
      dockerfile: DbMigration/Dockerfile
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "User ID =user-vTools-dev;Password=password;Server=db;Port=5432;Database=vTools;Pooling=true;"
