services:
#  db:
#    image: postgres:alpine
#    environment:
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_DB: vTools
#    ports:
#      - 5432:5432
#  dbmigration:
#    image: dbmigration:latest
#    build:
#      context: .
#      dockerfile: DbMigration/Dockerfile
#    depends_on:
#      - db
#    environment:
#      ConnectionStrings__DefaultConnection: "User ID =${DB_USER};Password=${DB_PASSWORD};Server=db;Port=5432;Database=vTools;Pooling=true;"

  VTools:
    image: vtools:latest
    build:
      context: .
      dockerfile: VTools/Dockerfile
    ports:
      - 7850:8080
#    depends_on:
#      - db
    environment:
      ConnectionStrings__DefaultConnection: "User ID =${DB_USER};Password=${DB_PASSWORD};Server=db;Port=5432;Database=vTools;Pooling=true;"
